/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_project.hospitalmanagementsystem;

import java.awt.*;
import java.io.*;
import java.nio.file.*;
import javax.swing.*;

/**
 *
 * @author hp
 */
public class PatientsInformation extends javax.swing.JFrame {

    /**
     * Creates new form PatientsInformation
     */
    public PatientsInformation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PatInfoHeaderPanel = new javax.swing.JPanel();
        PatInfoHeader = new javax.swing.JLabel();
        PatInfoMainPanel = new javax.swing.JPanel();
        PatNameText = new javax.swing.JLabel();
        PatIDText = new javax.swing.JLabel();
        PatPasswordText = new javax.swing.JLabel();
        PatExperienceText = new javax.swing.JLabel();
        PatIDField = new javax.swing.JTextField();
        PatPathField = new javax.swing.JTextField();
        PatAgeField = new javax.swing.JTextField();
        PatAddressField = new javax.swing.JTextField();
        PatDeleteButton = new javax.swing.JButton();
        PatClearButton = new javax.swing.JButton();
        PatAddButton = new javax.swing.JButton();
        PatDisplayButton = new javax.swing.JButton();
        PatRecord = new javax.swing.JLabel();
        PatHomeButton = new javax.swing.JButton();
        PatNameField = new javax.swing.JTextField();
        PatExperienceText1 = new javax.swing.JLabel();
        PatExperienceText2 = new javax.swing.JLabel();
        PatContactField = new javax.swing.JTextField();
        PatExperienceText3 = new javax.swing.JLabel();
        PatExperienceText4 = new javax.swing.JLabel();
        PatBloodGroupDropDown = new javax.swing.JComboBox<>();
        PatGenderDropDown = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        PatRecDisplay = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient's Information");
        setUndecorated(true);

        PatInfoHeader.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\HospitalManagementSystem\\img\\Patient's information.png")); // NOI18N

        javax.swing.GroupLayout PatInfoHeaderPanelLayout = new javax.swing.GroupLayout(PatInfoHeaderPanel);
        PatInfoHeaderPanel.setLayout(PatInfoHeaderPanelLayout);
        PatInfoHeaderPanelLayout.setHorizontalGroup(
            PatInfoHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PatInfoHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PatInfoHeaderPanelLayout.setVerticalGroup(
            PatInfoHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PatInfoHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PatInfoMainPanel.setBackground(new java.awt.Color(255, 255, 255));

        PatNameText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        PatNameText.setForeground(new java.awt.Color(255, 51, 255));
        PatNameText.setText("Patient's Name:");

        PatIDText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        PatIDText.setForeground(new java.awt.Color(255, 51, 255));
        PatIDText.setText("Patient's ID:");

        PatPasswordText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        PatPasswordText.setForeground(new java.awt.Color(255, 51, 255));
        PatPasswordText.setText("Pathologies:");

        PatExperienceText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        PatExperienceText.setForeground(new java.awt.Color(255, 51, 255));
        PatExperienceText.setText("Address:");

        PatIDField.setBackground(new java.awt.Color(255, 51, 255));
        PatIDField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PatIDField.setForeground(new java.awt.Color(255, 255, 255));

        PatPathField.setBackground(new java.awt.Color(255, 51, 255));
        PatPathField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PatPathField.setForeground(new java.awt.Color(255, 255, 255));

        PatAgeField.setBackground(new java.awt.Color(255, 51, 255));
        PatAgeField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PatAgeField.setForeground(new java.awt.Color(255, 255, 255));
        PatAgeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatAgeFieldActionPerformed(evt);
            }
        });

        PatAddressField.setBackground(new java.awt.Color(255, 51, 255));
        PatAddressField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PatAddressField.setForeground(new java.awt.Color(255, 255, 255));

        PatDeleteButton.setBackground(new java.awt.Color(255, 51, 255));
        PatDeleteButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        PatDeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        PatDeleteButton.setText("DELETE");
        PatDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatDeleteButtonActionPerformed(evt);
            }
        });

        PatClearButton.setBackground(new java.awt.Color(255, 51, 255));
        PatClearButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        PatClearButton.setForeground(new java.awt.Color(255, 255, 255));
        PatClearButton.setText("CLEAR");
        PatClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatClearButtonActionPerformed(evt);
            }
        });

        PatAddButton.setBackground(new java.awt.Color(255, 51, 255));
        PatAddButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        PatAddButton.setForeground(new java.awt.Color(255, 255, 255));
        PatAddButton.setText("ADD");
        PatAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatAddButtonActionPerformed(evt);
            }
        });

        PatDisplayButton.setBackground(new java.awt.Color(255, 51, 255));
        PatDisplayButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        PatDisplayButton.setForeground(new java.awt.Color(255, 255, 255));
        PatDisplayButton.setText("DISPLAY");
        PatDisplayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatDisplayButtonActionPerformed(evt);
            }
        });

        PatRecord.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\HospitalManagementSystem\\img\\Patients's Records.png")); // NOI18N

        PatHomeButton.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        PatHomeButton.setForeground(new java.awt.Color(255, 0, 255));
        PatHomeButton.setText("HOME");
        PatHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatHomeButtonActionPerformed(evt);
            }
        });

        PatNameField.setBackground(new java.awt.Color(255, 51, 255));
        PatNameField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PatNameField.setForeground(new java.awt.Color(255, 255, 255));

        PatExperienceText1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        PatExperienceText1.setForeground(new java.awt.Color(255, 51, 255));
        PatExperienceText1.setText("Age:");

        PatExperienceText2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        PatExperienceText2.setForeground(new java.awt.Color(255, 51, 255));
        PatExperienceText2.setText("Contact:");

        PatContactField.setBackground(new java.awt.Color(255, 51, 255));
        PatContactField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PatContactField.setForeground(new java.awt.Color(255, 255, 255));
        PatContactField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatContactFieldActionPerformed(evt);
            }
        });

        PatExperienceText3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        PatExperienceText3.setForeground(new java.awt.Color(255, 51, 255));
        PatExperienceText3.setText("Blood:");

        PatExperienceText4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        PatExperienceText4.setForeground(new java.awt.Color(255, 51, 255));
        PatExperienceText4.setText("Gender:");

        PatBloodGroupDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        PatBloodGroupDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatBloodGroupDropDownActionPerformed(evt);
            }
        });

        PatGenderDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", "Other" }));

        PatRecDisplay.setBackground(new java.awt.Color(255, 0, 204));
        PatRecDisplay.setColumns(20);
        PatRecDisplay.setRows(5);
        jScrollPane1.setViewportView(PatRecDisplay);

        javax.swing.GroupLayout PatInfoMainPanelLayout = new javax.swing.GroupLayout(PatInfoMainPanel);
        PatInfoMainPanel.setLayout(PatInfoMainPanelLayout);
        PatInfoMainPanelLayout.setHorizontalGroup(
            PatInfoMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PatInfoMainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PatHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(401, 401, 401))
            .addComponent(PatRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PatInfoMainPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(PatInfoMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PatPasswordText)
                    .addComponent(PatNameText)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PatInfoMainPanelLayout.createSequentialGroup()
                        .addComponent(PatIDText)
                        .addGap(45, 45, 45)))
                .addGroup(PatInfoMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PatInfoMainPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(PatAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(PatDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PatInfoMainPanelLayout.createSequentialGroup()
                        .addGroup(PatInfoMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PatPathField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatNameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatIDField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(PatInfoMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PatInfoMainPanelLayout.createSequentialGroup()
                                .addComponent(PatExperienceText2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PatInfoMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PatInfoMainPanelLayout.createSequentialGroup()
                                        .addComponent(PatDisplayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)
                                        .addComponent(PatClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PatInfoMainPanelLayout.createSequentialGroup()
                                        .addComponent(PatContactField)
                                        .addGap(51, 51, 51))))
                            .addGroup(PatInfoMainPanelLayout.createSequentialGroup()
                                .addGroup(PatInfoMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PatExperienceText)
                                    .addComponent(PatExperienceText1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PatInfoMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PatAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PatAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(PatInfoMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PatExperienceText4)
                                    .addComponent(PatExperienceText3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PatInfoMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PatBloodGroupDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PatGenderDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        PatInfoMainPanelLayout.setVerticalGroup(
            PatInfoMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatInfoMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PatInfoMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatIDText)
                    .addComponent(PatIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatExperienceText)
                    .addComponent(PatAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatExperienceText3)
                    .addComponent(PatBloodGroupDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(PatInfoMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatNameText)
                    .addComponent(PatNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatExperienceText1)
                    .addComponent(PatAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatExperienceText4)
                    .addComponent(PatGenderDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PatInfoMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PatInfoMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PatPasswordText)
                        .addComponent(PatExperienceText2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PatInfoMainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PatInfoMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PatPathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatContactField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PatInfoMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatDisplayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PatRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PatHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PatInfoHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PatInfoMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PatInfoHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PatInfoMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PatDisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatDisplayButtonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String id = PatIDField.getText();
            Path show = Path.of(id+".txt");
            String textString = Files.readString(show);
            PatRecDisplay.setText(textString);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error 202 : Read Error !!!");
        }
    }//GEN-LAST:event_PatDisplayButtonActionPerformed

    private void PatAgeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatAgeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatAgeFieldActionPerformed

    private void PatContactFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatContactFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatContactFieldActionPerformed

    private void PatBloodGroupDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatBloodGroupDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatBloodGroupDropDownActionPerformed

    private void PatHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatHomeButtonActionPerformed
        // TODO add your handling code here:
        HomePage e = new HomePage();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PatHomeButtonActionPerformed

    private void PatDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatDeleteButtonActionPerformed
        // TODO add your handling code here:
        String t = PatIDField.getText();
        File file = new File(t+".txt");
        file.delete();
        JOptionPane.showMessageDialog(null, "Record Deleted Successfully");
    }//GEN-LAST:event_PatDeleteButtonActionPerformed

    private void PatClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatClearButtonActionPerformed
        // TODO add your handling code here:
        PatIDField.setText(null);
        PatPathField.setText(null);
        PatAddressField.setText(null);
        PatNameField.setText(null);
        PatContactField.setText(null);
        PatAgeField.setText(null);
    }//GEN-LAST:event_PatClearButtonActionPerformed

    private void PatAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatAddButtonActionPerformed
        // TODO add your handling code here:
        String i = PatIDField.getText();
        String p = PatPathField.getText();
        String a = PatAddressField.getText();
        String n = PatNameField.getText();
        String c = PatContactField.getText();
        String age = PatAgeField.getText();
        String b = (String) PatBloodGroupDropDown.getSelectedItem();
        String g = (String) PatGenderDropDown.getSelectedItem();
        
        try (FileWriter Writer = new FileWriter(i+".txt", true)) {
            Writer.write("**** Patient Information ****");
            
            Writer.write(System.lineSeparator());
            Writer.write(System.lineSeparator());
            
            Writer.write(">> ID: "+i);
            Writer.write(System.lineSeparator());
            Writer.write(">> Name: "+n);
            Writer.write(System.lineSeparator());
            Writer.write(">> Pathologies: "+p);
            Writer.write(System.lineSeparator());
            Writer.write(">> Address: "+a);
            Writer.write(System.lineSeparator());
            Writer.write(">> Age: "+age);
            Writer.write(System.lineSeparator());
            Writer.write(">> Contact: "+c);
            Writer.write(System.lineSeparator());
            Writer.write(">> Blood Group: "+b);
            Writer.write(System.lineSeparator());
            Writer.write(">> Gender: "+g);
            

            JOptionPane.showMessageDialog(null, "Successfully Recorded");
            setVisible(false);
            new PatientsInformation().setVisible(true);

        }catch(HeadlessException | IOException e){
            JOptionPane.showMessageDialog(null, "Error 404 !!!");
        }
        
    }//GEN-LAST:event_PatAddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientsInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientsInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientsInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientsInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientsInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PatAddButton;
    private javax.swing.JTextField PatAddressField;
    private javax.swing.JTextField PatAgeField;
    private javax.swing.JComboBox<String> PatBloodGroupDropDown;
    private javax.swing.JButton PatClearButton;
    private javax.swing.JTextField PatContactField;
    private javax.swing.JButton PatDeleteButton;
    private javax.swing.JButton PatDisplayButton;
    private javax.swing.JLabel PatExperienceText;
    private javax.swing.JLabel PatExperienceText1;
    private javax.swing.JLabel PatExperienceText2;
    private javax.swing.JLabel PatExperienceText3;
    private javax.swing.JLabel PatExperienceText4;
    private javax.swing.JComboBox<String> PatGenderDropDown;
    private javax.swing.JButton PatHomeButton;
    private javax.swing.JTextField PatIDField;
    private javax.swing.JLabel PatIDText;
    private javax.swing.JLabel PatInfoHeader;
    private javax.swing.JPanel PatInfoHeaderPanel;
    private javax.swing.JPanel PatInfoMainPanel;
    private javax.swing.JTextField PatNameField;
    private javax.swing.JLabel PatNameText;
    private javax.swing.JLabel PatPasswordText;
    private javax.swing.JTextField PatPathField;
    private javax.swing.JTextArea PatRecDisplay;
    private javax.swing.JLabel PatRecord;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
