/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_project.hospitalmanagementsystem;

import java.awt.*;
import java.awt.print.PrinterException;
import java.io.*;
import java.nio.file.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author hp
 */
public class PaymentInformation extends javax.swing.JFrame {

    /**
     * Creates new form PaymentInformation
     */
    public PaymentInformation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PayHeaderPanel = new javax.swing.JPanel();
        PayHeader = new javax.swing.JLabel();
        PayMainPanel = new javax.swing.JPanel();
        DocNameText = new javax.swing.JLabel();
        PatID = new javax.swing.JLabel();
        PayDiseaseText = new javax.swing.JLabel();
        PayMedText = new javax.swing.JLabel();
        PatIDBox = new javax.swing.JTextField();
        PayDiseaseBox = new javax.swing.JTextField();
        PayBIBox = new javax.swing.JTextField();
        PayMedBox = new javax.swing.JTextField();
        PayDeleteButton = new javax.swing.JButton();
        PayClearButton = new javax.swing.JButton();
        PayAddButton = new javax.swing.JButton();
        PayRecord = new javax.swing.JLabel();
        DocIDFields = new javax.swing.JTextField();
        PayBillIDText = new javax.swing.JLabel();
        PayStayDayText = new javax.swing.JLabel();
        PayStayDayField = new javax.swing.JTextField();
        PayRoomTypeText = new javax.swing.JLabel();
        PatRoomTypeCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReportDisplay = new javax.swing.JTextArea();
        PayHomeButton = new javax.swing.JButton();
        ShowReportButton = new javax.swing.JButton();
        ClearScreensButton = new javax.swing.JButton();
        PrintReportButton = new javax.swing.JButton();
        PatTypeText = new javax.swing.JLabel();
        PatTypeBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PayHeader.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\HospitalManagementSystem\\img\\Payment Records.png")); // NOI18N

        PayMainPanel.setBackground(new java.awt.Color(0, 51, 0));

        DocNameText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        DocNameText.setForeground(new java.awt.Color(255, 255, 255));
        DocNameText.setText("Doctor's ID:");

        PatID.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        PatID.setForeground(new java.awt.Color(255, 255, 255));
        PatID.setText("Patient's ID:");

        PayDiseaseText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        PayDiseaseText.setForeground(new java.awt.Color(255, 255, 255));
        PayDiseaseText.setText("Disease:");

        PayMedText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        PayMedText.setForeground(new java.awt.Color(255, 255, 255));
        PayMedText.setText("Medicine:");

        PatIDBox.setBackground(new java.awt.Color(0, 51, 0));
        PatIDBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PatIDBox.setForeground(new java.awt.Color(255, 255, 255));

        PayDiseaseBox.setBackground(new java.awt.Color(0, 51, 0));
        PayDiseaseBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PayDiseaseBox.setForeground(new java.awt.Color(255, 255, 255));

        PayBIBox.setBackground(new java.awt.Color(0, 51, 0));
        PayBIBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PayBIBox.setForeground(new java.awt.Color(255, 255, 255));
        PayBIBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayBIBoxActionPerformed(evt);
            }
        });

        PayMedBox.setBackground(new java.awt.Color(0, 51, 0));
        PayMedBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PayMedBox.setForeground(new java.awt.Color(255, 255, 255));
        PayMedBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayMedBoxActionPerformed(evt);
            }
        });

        PayDeleteButton.setBackground(new java.awt.Color(0, 51, 0));
        PayDeleteButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        PayDeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        PayDeleteButton.setText("DELETE");
        PayDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayDeleteButtonActionPerformed(evt);
            }
        });

        PayClearButton.setBackground(new java.awt.Color(0, 51, 0));
        PayClearButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        PayClearButton.setForeground(new java.awt.Color(255, 255, 255));
        PayClearButton.setText("CLEAR");
        PayClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayClearButtonActionPerformed(evt);
            }
        });

        PayAddButton.setBackground(new java.awt.Color(0, 51, 0));
        PayAddButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        PayAddButton.setForeground(new java.awt.Color(255, 255, 255));
        PayAddButton.setText("ADD");
        PayAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayAddButtonActionPerformed(evt);
            }
        });

        PayRecord.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\HospitalManagementSystem\\img\\Paymet Records.png")); // NOI18N

        DocIDFields.setBackground(new java.awt.Color(0, 51, 0));
        DocIDFields.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        DocIDFields.setForeground(new java.awt.Color(255, 255, 255));

        PayBillIDText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        PayBillIDText.setForeground(new java.awt.Color(255, 255, 255));
        PayBillIDText.setText("Bill ID:");

        PayStayDayText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        PayStayDayText.setForeground(new java.awt.Color(255, 255, 255));
        PayStayDayText.setText("No. of Stay Days:");

        PayStayDayField.setBackground(new java.awt.Color(0, 51, 0));
        PayStayDayField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PayStayDayField.setForeground(new java.awt.Color(255, 255, 255));
        PayStayDayField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayStayDayFieldActionPerformed(evt);
            }
        });

        PayRoomTypeText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        PayRoomTypeText.setForeground(new java.awt.Color(255, 255, 255));
        PayRoomTypeText.setText("Room Type:");

        PatRoomTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Deluxe", "Private", "Semi Private" }));

        ReportDisplay.setBackground(new java.awt.Color(0, 51, 0));
        ReportDisplay.setColumns(20);
        ReportDisplay.setForeground(new java.awt.Color(255, 255, 255));
        ReportDisplay.setRows(5);
        ReportDisplay.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane1.setViewportView(ReportDisplay);

        PayHomeButton.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        PayHomeButton.setForeground(new java.awt.Color(0, 51, 0));
        PayHomeButton.setText("HOME");
        PayHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayHomeButtonActionPerformed(evt);
            }
        });

        ShowReportButton.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        ShowReportButton.setForeground(new java.awt.Color(0, 51, 0));
        ShowReportButton.setText("Display Report");
        ShowReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowReportButtonActionPerformed(evt);
            }
        });

        ClearScreensButton.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        ClearScreensButton.setForeground(new java.awt.Color(0, 51, 0));
        ClearScreensButton.setText("Clear Screen");
        ClearScreensButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearScreensButtonActionPerformed(evt);
            }
        });

        PrintReportButton.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        PrintReportButton.setForeground(new java.awt.Color(0, 51, 0));
        PrintReportButton.setText("Print Report");
        PrintReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintReportButtonActionPerformed(evt);
            }
        });

        PatTypeText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        PatTypeText.setForeground(new java.awt.Color(255, 255, 255));
        PatTypeText.setText("Patient Type:");

        PatTypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "DSU", "Non-DSU" }));

        javax.swing.GroupLayout PayMainPanelLayout = new javax.swing.GroupLayout(PayMainPanel);
        PayMainPanel.setLayout(PayMainPanelLayout);
        PayMainPanelLayout.setHorizontalGroup(
            PayMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PayRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PayMainPanelLayout.createSequentialGroup()
                .addGroup(PayMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PayMainPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(PayMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PayDiseaseText)
                            .addComponent(DocNameText)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PayMainPanelLayout.createSequentialGroup()
                                .addComponent(PatID)
                                .addGap(45, 45, 45)))
                        .addGroup(PayMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PayDiseaseBox, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DocIDFields, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PayMainPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(PayAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(PayMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PayMainPanelLayout.createSequentialGroup()
                                .addComponent(PayDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(PayClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PayMainPanelLayout.createSequentialGroup()
                                .addGroup(PayMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PayMainPanelLayout.createSequentialGroup()
                                        .addComponent(PayStayDayText)
                                        .addGap(18, 18, 18)
                                        .addComponent(PayStayDayField))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PayMainPanelLayout.createSequentialGroup()
                                        .addGroup(PayMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PayMedText)
                                            .addComponent(PayBillIDText))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PayMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PayBIBox, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PayMedBox, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(37, 37, 37)
                                .addGroup(PayMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PayRoomTypeText)
                                    .addComponent(PatRoomTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PayMainPanelLayout.createSequentialGroup()
                                        .addComponent(PatTypeText)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PatTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(PayMainPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(PayMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ShowReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PrintReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(PayMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ClearScreensButton, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(PayHomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PayMainPanelLayout.setVerticalGroup(
            PayMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PayMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PayMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PayMainPanelLayout.createSequentialGroup()
                        .addGroup(PayMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatID)
                            .addComponent(PatIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PayMedText)
                            .addComponent(PayMedBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PayMainPanelLayout.createSequentialGroup()
                        .addComponent(PayRoomTypeText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(PayMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DocNameText)
                    .addComponent(DocIDFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PayBillIDText)
                    .addComponent(PayBIBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatRoomTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PayMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PayMainPanelLayout.createSequentialGroup()
                        .addGroup(PayMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PayDiseaseBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PayDiseaseText))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PayMainPanelLayout.createSequentialGroup()
                        .addGroup(PayMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PayStayDayField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PayStayDayText)
                            .addComponent(PatTypeText)
                            .addComponent(PatTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(PayMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PayAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PayMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PayClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PayDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PayMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PayMainPanelLayout.createSequentialGroup()
                        .addComponent(PayRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PayMainPanelLayout.createSequentialGroup()
                        .addComponent(PrintReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(ShowReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PayMainPanelLayout.createSequentialGroup()
                        .addComponent(ClearScreensButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(PayHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );

        javax.swing.GroupLayout PayHeaderPanelLayout = new javax.swing.GroupLayout(PayHeaderPanel);
        PayHeaderPanel.setLayout(PayHeaderPanelLayout);
        PayHeaderPanelLayout.setHorizontalGroup(
            PayHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PayHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PayHeaderPanelLayout.createSequentialGroup()
                .addComponent(PayMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PayHeaderPanelLayout.setVerticalGroup(
            PayHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PayHeaderPanelLayout.createSequentialGroup()
                .addComponent(PayHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PayMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PayHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PayHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PayBIBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayBIBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PayBIBoxActionPerformed

    private void PayDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayDeleteButtonActionPerformed
        // TODO add your handling code here:
        String t = PayBIBox.getText();
        File files = new File (t+"-report.txt");
        files.delete();
      
        JOptionPane.showMessageDialog(null, "Record Deleted Successfully");
    }//GEN-LAST:event_PayDeleteButtonActionPerformed

    private void PayClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayClearButtonActionPerformed
        // TODO add your handling code here:
        PatIDBox.setText(null);
        PayBIBox.setText(null);
        PayMedBox.setText(null);
        DocIDFields.setText(null);
        PayStayDayField.setText(null);
        PayDiseaseBox.setText(null);
    }//GEN-LAST:event_PayClearButtonActionPerformed

    private void PayAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayAddButtonActionPerformed
        try {                                             
            // TODO add your handling code here:
            String i = PatIDBox.getText();
            String b = PayBIBox.getText();
            String m = PayMedBox.getText();
            String n = DocIDFields.getText();
            String sd = PayStayDayField.getText();
            String d = PayDiseaseBox.getText();
            String rt = (String) PatRoomTypeCombo.getSelectedItem();
            String pt = (String) PatTypeBox.getSelectedItem();
            int amount=10000;
            if ("Deluxe".equals(rt)){
                amount*=10;
            }
            else if ("Private".equals(rt)){
                amount*=4;
            }
            int days=Integer.parseInt(sd);
            amount*=days;
            
            if ("DSU".equals(pt)){
                amount -= (amount/10);
            }
            int Grand = amount+30000;
            Path Pshow = Path.of(i+".txt");
            String PatText = Files.readString(Pshow);
            
            Path Dshow = Path.of(n+".txt");
            String DocText = Files.readString(Dshow);
            
            try (FileWriter put = new FileWriter(b+"-report.txt", true)) {
                put.write("**** PATIENT FINAL REPORT ****");
                put.write(System.lineSeparator());
                put.write(System.lineSeparator());
                put.write(PatText);
                put.write(System.lineSeparator());
                put.write(System.lineSeparator());
                put.write(DocText);
                put.write(System.lineSeparator());
                put.write("> Disease Daignosed: "+d+"  >Medicine Provided: "+m);
                put.write(System.lineSeparator());
                put.write(">> BILL ID "+b+" <<");
                put.write(System.lineSeparator());
                put.write(">> No. of Days Admit (Patient): "+sd);
                put.write(System.lineSeparator());
                put.write(">> Admit Room Type: "+rt);
                put.write(System.lineSeparator());
                put.write(">> Patient Type: "+pt);
                put.write(System.lineSeparator());             
                put.write(System.lineSeparator());
                put.write("Base Charges for Daignosis & Medicine = Rs. 10000");
                put.write(System.lineSeparator());
                put.write("Room Charges * Number of Stay Days = Rs. "+amount);
                put.write(System.lineSeparator());
                put.write("Doctor Fees = Rs. 20000");
                put.write(System.lineSeparator());
                put.write(System.lineSeparator());
                put.write("--------------------  ");
                put.write("Total Bill =  Rs. "+Grand);
                put.write("  --------------------");
                put.write(System.lineSeparator());
                put.write(System.lineSeparator());
                put.write("** 10% Discount already calculated if DSU **");
                put.write(System.lineSeparator());
                put.write("-----------------  END  -----------------");
                              
                JOptionPane.showMessageDialog(null, "Successfully Recorded");
                setVisible(false);
                new PaymentInformation().setVisible(true);
                
            }catch(HeadlessException | IOException e){
                JOptionPane.showMessageDialog(null, "Error 404 !!!");
            }
            
        }catch(IOException ex){
            Logger.getLogger(PaymentInformation.class.getName()).log(Level.SEVERE,null, ex);
        }

    }//GEN-LAST:event_PayAddButtonActionPerformed

    private void PayStayDayFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayStayDayFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PayStayDayFieldActionPerformed

    private void PayHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayHomeButtonActionPerformed
        // TODO add your handling code here:
        HomePage v = new HomePage();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PayHomeButtonActionPerformed

    private void PayMedBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayMedBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PayMedBoxActionPerformed

    private void ShowReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowReportButtonActionPerformed
        // TODO add your handling code here:
        try {
            String bill = PayBIBox.getText();
            Path show = Path.of(bill+"-report.txt");
            String billrep = Files.readString(show);
            ReportDisplay.setText(billrep);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error 202 : Read Error !!!");
        }
        
    }//GEN-LAST:event_ShowReportButtonActionPerformed

    private void ClearScreensButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearScreensButtonActionPerformed
        // TODO add your handling code here:
        ReportDisplay.setText(null);
    }//GEN-LAST:event_ClearScreensButtonActionPerformed

    private void PrintReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintReportButtonActionPerformed
        // TODO add your handling code here:
        try{
            boolean complete = ReportDisplay.print();
            if (complete) {
                JOptionPane.showMessageDialog(null, "Print Successful", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(null, "Print Un Successful", "Printer Error", JOptionPane.ERROR_MESSAGE);
            }
        }catch(PrinterException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_PrintReportButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearScreensButton;
    private javax.swing.JTextField DocIDFields;
    private javax.swing.JLabel DocNameText;
    private javax.swing.JLabel PatID;
    private javax.swing.JTextField PatIDBox;
    private javax.swing.JComboBox<String> PatRoomTypeCombo;
    private javax.swing.JComboBox<String> PatTypeBox;
    private javax.swing.JLabel PatTypeText;
    private javax.swing.JButton PayAddButton;
    private javax.swing.JTextField PayBIBox;
    private javax.swing.JLabel PayBillIDText;
    private javax.swing.JButton PayClearButton;
    private javax.swing.JButton PayDeleteButton;
    private javax.swing.JTextField PayDiseaseBox;
    private javax.swing.JLabel PayDiseaseText;
    private javax.swing.JLabel PayHeader;
    private javax.swing.JPanel PayHeaderPanel;
    private javax.swing.JButton PayHomeButton;
    private javax.swing.JPanel PayMainPanel;
    private javax.swing.JTextField PayMedBox;
    private javax.swing.JLabel PayMedText;
    private javax.swing.JLabel PayRecord;
    private javax.swing.JLabel PayRoomTypeText;
    private javax.swing.JTextField PayStayDayField;
    private javax.swing.JLabel PayStayDayText;
    private javax.swing.JButton PrintReportButton;
    private javax.swing.JTextArea ReportDisplay;
    private javax.swing.JButton ShowReportButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
